name: gpt2_viet_poem_final_pytorch
location: asia-southeast1
storageClass: STANDARD
versioning:
  enabled: true
iamConfiguration:
  uniformBucketLevelAccess: true
  publicAccessPrevention: enforced
lifecycle:
  rule:
    - action:
        type: Delete
      condition:
        age: 365
        numNewerVersions: 3
cors:
  - origin: ["*"]
    method: ["GET", "HEAD", "PUT", "POST", "DELETE"]
    responseHeader: ["Content-Type", "Access-Control-Allow-Origin"]
    maxAgeSeconds: 3600 