apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: poem-frontend
spec:
  template:
    spec:
      containers:
        - image: gcr.io/$PROJECT_ID/poem-frontend:latest
          ports:
            - containerPort: 8080
          env:
            - name: NEXT_PUBLIC_API_URL
              value: https://api.poem.example.com
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
      containerConcurrency: 80
      timeoutSeconds: 300
  traffic:
    - percent: 100
      latestRevision: true 