version: '3'

services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - MODEL_BUCKET=gpt2_viet_poem_final_pytorch
      - PORT=8080
    volumes:
      - ./credentials.json:/app/credentials.json
    networks:
      - poem-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NODE_ENV=production
      - PORT=8080
    depends_on:
      - backend
    networks:
      - poem-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  poem-network:
    driver: bridge 